algorithm: 'CCE-MASAC'
seed: 666
agent_number: 4
actor_learning_rate : 0.00005
critic_learning_rate: 0.0001
constrainted_critic_learning_rate: 0.0001
gamma: 0.99
hidden_dim: 128
epochs: 10
buffer_batchsize: 32
mini_batch: 8
episodes: 200
offset: 5
alpha_learning_rate: 0.00005
density_learning_rate: 0.0001
tau: 0.005
beta_coef: 0.1
kld_weight: 0.00025
eta_coef1: 0.05
eta_coef2: 0.05