algorithm: 'MASAC'
seed: 666
agent_number: 5
actor_learning_rate : 0.00005
critic_learning_rate: 0.0001
alpha_learning_rate: 0.00005
gamma: 0.99
lamda: 0.97
hidden_dim: 128
entropy_coef: 0.005
epochs: 10
buffer_batchsize: 32
episodes: 500
offset: 5
tau: 0.005
kld_weight: 0.00025