root: /root/paddlejob/workspace/rongxiao/Argoverse2
model: QCNet
batch_size: 1
# shuffle: True
num_workers: 160
pin_memory: True
persistent_workers: True
accelerator: auto
devices: [0]
teacher_forcing: False
num_historical_steps: 10
num_future_steps: 100

checkpoint_path: /root/paddlejob/workspace/rongxiao/Multi-agent-Inverse-Constraint-Reinforcement-Learning/lightning_logs/version_88/checkpoints/epoch=0-step=40000.ckpt

QCNet:
  dataset: argoverse_v2
  input_dim: 2
  hidden_dim: 128
  output_dim: 2
  output_head: True
  num_historical_steps: 10
  num_future_steps: 100
  num_modes: 1
  num_recurrent_steps: 1
  num_freq_bands: 64
  num_map_layers: 1
  num_agent_layers: 2
  num_dec_layers: 2
  num_heads: 8
  head_dim: 16
  dropout: 0.1
  pl2pl_radius: 150
  time_span: 10
  pl2a_radius: 50
  a2a_radius: 50
  num_t2m_steps: 30
  pl2m_radius: 150
  a2m_radius: 50 # reduced from 150
  lr: 0.0003
  weight_decay: 0.0001
  T_max: 64
  submission_dir: ./
  submission_file_name: submission
  evaluate_type: auto_regressive
  agent_limit: 15
  
